name: Discord Commit Notifications

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main, master ]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL_RATATOSKR }}
        with:
          args: |
            **A messanger scampers down Yggdrasil's branches!**
            
            **Realm:** `${{ github.repository }}`
            **Branch:** `${{ github.ref_name }}`
            **Skald:** `${{ github.actor }}`
            **Commit:** `${{ github.sha }}`
          
            **Whispers from the bark:**
            ```
            ${{ github.event.head_commit.message }}
            ```
            
            **Follow my path to see the change:** ${{ github.event.compare }}